Repository uncovertruth/fuji, pull requests merged in 2018-02, with the labels that each got.

#25 Blog new design
  .editorconfig
  .eslintrc.json
  .stylelintignore
  .stylelintrc.json
  .travis.yml
  README.md
  package.json
  src/amp.hbs
  src/assets/fonts/icons/fonts/icons.eot
  src/assets/fonts/icons/fonts/icons.svg
  src/assets/fonts/icons/fonts/icons.ttf
  src/assets/fonts/icons/fonts/icons.woff
  src/assets/fonts/icons/icons.css
  src/assets/images/ut-logo.svg
  src/assets/style.css
  src/default.hbs
  src/index.hbs
  src/partials/breadcrumb.hbs
  src/partials/footer.hbs
  src/partials/header.hbs
  src/partials/loop.hbs
  src/partials/navigation.hbs
  src/partials/pagination.hbs
  src/partials/right-column.hbs
  src/partials/widget-share.hbs
  src/post.hbs
  src/scss/_Base.scss
  src/scss/_Blockquote.scss
  src/scss/_Breadcrumb.scss
  src/scss/_Breakpoint.scss
  src/scss/_Code.scss
  src/scss/_Footer.scss
  src/scss/_Form.scss
  src/scss/_Image.scss
  src/scss/_Link.scss
  src/scss/_List.scss
  src/scss/_Loop.scss
  src/scss/_Misc.scss
  src/scss/_Navigation.scss
  src/scss/_Pagination.scss
  src/scss/_Post.scss
  src/scss/_Social.scss
  src/scss/_Table.scss
  src/scss/amp/amp.scss
  src/scss/screen.scss
  src/tag.hbs
Labels: enhancement, in progress

#30 Amp scss
  src/amp.hbs
  src/scss/amp/amp.scss
Labels: in progress

#31 chore(package) set v1.0.0
  package.json
Labels: in progress

#32 Fixed amp styles
  package.json
  src/amp.hbs
  src/partials/loop.hbs
  src/post.hbs
  src/scss/_Breadcrumb.scss
  src/scss/_Loop.scss
  src/scss/_Post.scss
  src/scss/amp/amp.scss
Labels: in progress

#33 chore(src) Added google analytics tracking
  package.json
  src/amp.hbs
Labels: in progress

#34 amp比率変更
  src/amp.hbs
Labels: in progress

#35 chore(package) set v1.1.1
  package.json
Labels: in progress

#36 fix(src) Fixed load amp-analytics
  package.json
  src/amp.hbs
Labels: QA, bug
